/**
 * Registers the bundled flag icons with Iconify's local registry
 *
 * @iconify/svelte resolves an unknown icon name by calling api.iconify.design,
 * which means a third-party request on first render and no icon at all during
 * SSR. Pre-registering the codes in KNOWN_REGION_CODES means those render
 * straight from the bundle; anything else still falls back to the API
 *
 * The JSON is generated by scripts/build-flag-icons.js
 */
import { addCollection } from '@iconify/svelte/dist/functions'
import bundle from './generated/flag-icons.json'

// ES modules evaluate once per runtime, so this registers exactly once
for (const collection of bundle.collections) {
	addCollection(/** @type {import('@iconify/types').IconifyJSON} */ (/** @type {unknown} */ (collection)))
}

/** Number of flag icons available without hitting the network */
export const BUNDLED_FLAG_COUNT = bundle.collections
	.reduce((n, c) => n + Object.keys(c.icons).length, 0)
