/**
 * Registers the bundled UI icons with Iconify's local registry
 *
 * @iconify/svelte resolves an unknown icon name by calling api.iconify.design:
 * a third-party request per icon on first render, nothing during SSR, and icons
 * that pop in after hydration. Registering the bundle up front means every icon
 * the components name renders from our own JS, server-side included
 *
 * The JSON is generated by scripts/build-icons.js, which fails the build if a
 * component names an icon that is not in its set
 */
import { addCollection } from '@iconify/svelte/dist/functions'
import bundle from './generated/ui-icons.json'

// ES modules evaluate once per runtime, so this registers exactly once
for (const collection of bundle.collections) {
	addCollection(/** @type {import('@iconify/types').IconifyJSON} */ (/** @type {unknown} */ (collection)))
}

/** Number of UI icons available without hitting the network */
export const BUNDLED_UI_ICON_COUNT = bundle.collections
	.reduce((n, c) => n + Object.keys(c.icons).length, 0)
